# graph.py

import dash
from dash import dcc, html
from dash.dependencies import Input, Output
import pandas as pd
import plotly.graph_objects as go
from sqlalchemy import create_engine, Column, String, Integer, Float, Text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from dotenv import load_dotenv
import os

def roman_to_int(roman_str):
    roman_numerals = {
        'I': 1, 'II': 2, 'III': 3, 'IV': 4, 'V': 5,
        'VI': 6, 'VII': 7, 'VIII': 8, 'IX': 9, 'X': 10
    }
    value = roman_numerals.get(roman_str)
    return value

# Function to convert intensity ranges into an average value
def parse_intensity(intensity_all):
    result = []
    # Detect if it's a range or a single value
    for intensity in intensity_all:
        if '/' in intensity:
            parts = intensity.split('/')
            values = [roman_to_int(part) for part in parts]
            result.append(int(sum(values) / 2))  # Returns the average of the values
        elif 'Sem info a esta hora' in intensity:
            result.append(1) # Default value
        else:
            result.append(int(roman_to_int(intensity)))  # Returns the integer value
    return result

def update_data():
    # Reopen the session to ensure new data is captured
    Session = sessionmaker(bind=engine)
    session = Session()

    # Get current data from the database and convert it to a DataFrame
    database = session.query(Earthquake).all()
    data = [item.__dict__ for item in database]
    
    # Remove the _sa_instance_state key generated by SQLAlchemy
    for item in data:
        item.pop('_sa_instance_state', None)
    
    db_df = pd.DataFrame(data)
    session.close()
    return db_df

Base = declarative_base()
class Earthquake(Base):
    __tablename__ = "earthquake"
    id = Column("id", Integer, primary_key=True, autoincrement="auto")
    title = Column("title", Text)
    description = Column("description", Text)
    pub_date = Column("publication_date", String(25))
    date = Column("date_time", String(50))
    scale = Column("scale", Float)
    location = Column("location", String(255))
    intensity = Column("intensity", String(255))
    latitude = Column("latitude", Float)
    longitude = Column('longitude', Float)

    def __init__(self, id, title, description, pub_date, date, scale, location, intensity, latitude, longitude):
        self.id = id
        self.title = title
        self.description = description
        self.pub_date = pub_date
        self.date = date
        self.scale = scale
        self.location = location
        self.intensity = intensity
        self.latitude = latitude
        self.longitude = longitude

    def __repr__(self):
        return f"({self.id}) ({self.title}) ({self.description}) ({self.pub_date}) ({self.date}) ({self.scale}) ({self.location}) ({self.intensity}) ({self.latitude}) ({self.longitude})"

# Title of the APP
title = "AterraTreme Dashboard"

# Initialize the Dash application
app = dash.Dash(__name__)
app.title = title

# Load sensitive information
load_dotenv('.env')
host = os.getenv('host')
user = os.getenv('user')
password = os.getenv('password')
database = os.getenv('database')

# Establish the connection to the server
engine = create_engine(f"mysql+pymysql://{user}:{password}@{host}/{database}?charset=utf8mb4")
Base = declarative_base()

# Add styles to the App
app.css.append_css({
    'external_url': './assets/style.css'
})

# Layout of the Dash app
app.layout = html.Div(
    className='div-principal',
    children=[
        html.Div(
            id='info-div',
            className='info-div',
            children=[
                html.H1(title),
                # Dropdown for title selection
                html.Div(
                    id='more-info-div',
                    children=[
                        dcc.Dropdown(
                            id='title-dropdown',
                            options=[],
                            value=None,  # Initial value
                            className='dropdown'
                        ),
                        html.Br(),
                        # Div to display description and publication date
                        html.Div(id='description-date', className='description'),
                        html.Br(),
                        dcc.Markdown(
                            className='more-info',
                            children=[
                                '''
                                #### Data extracted from [IPMA](https://www.ipma.pt)
                                '''
                            ]
                        ),
                        html.A(
                            href='https://www.ipma.pt/',
                            id='img-ipma',
                            className='img-ipma',
                            children=[
                                html.P(
                                    'Data extracted from'
                                ),
                                html.Img(
                                    alt='ipma-logo',
                                    src='https://www.ipma.pt/opencms/system/modules/ipma.website/resources/images/logo-ipma-17.svg',
                                ),
                            ]
                        )
                    ]
                ),
                dcc.Store(id='hide-store', data={'hide': False}),  # Store the hide state
            ]
        ),
        html.Div(
            id='map-container',
            className='div-mapa',
            children=[
                # Map to show the location of earthquakes
                dcc.Graph(id='map', className='mapa'),
            ]
        ),
        html.Div(
            className='mobile-info',
            children=[
                html.Button(
                    id='triguer',
                    className='mobile-triguer-info',
                    children=[
                        html.P(
                            "Earthquake Information"
                        )
                    ]
                )
            ]
        ),
        # Interval to update the data
        dcc.Interval(
            id='interval-component',
            interval=60*3000,  # Update every 5 minutes
            n_intervals=0
        )
    ]
)

# Callback to update the dropdown options and the map
@app.callback(
    [Output('title-dropdown', 'options'),
     Output('title-dropdown', 'value'),
     Output('map', 'figure')],
    [Input('interval-component', 'n_intervals')]
)
def update_dropdown_and_map(n_intervals):
    df = update_data()
    dropdown_options = [{'label': date, 'value': date} for date in df['date']]
    if not df.empty:
        initial_value = df['date'].iloc[-1]
    else:
        initial_value = None

    custom_colors = [
        "#006400",  # Green
        "#00FF00",  # Lime
        "#ffbf00",  # Yellow
        "#ff4000",  # Orange
        "#ff0000",  # Red
    ]

    # Initialize the figure
    fig = go.Figure()
    image = go.Figure()

    # Add trace to the map
    fig.add_trace(go.Scattermapbox(
        lat=df['latitude'],
        lon=df['longitude'],
        mode='markers',
        marker=dict(
            size=(df['scale'] ** 2.5) + 5,  # Adjust marker size
            color=parse_intensity(df['intensity']),  # Colors based on intensity
            colorscale=custom_colors,  # Custom color scale
            colorbar=dict(
                tickvals=[1, 10],  # Color range values
                ticktext=['1', '10'],  # Color range labels
                title='Intensity'  # Color bar title
            ),
            cmin=1,  # Minimum value for color scale
            cmax=10,  # Maximum value for color scale
            showscale=True  # Show color bar
        ),
        customdata=df[['title', 'location', 'intensity', 'scale']],  # Custom data for hover
        hovertemplate=(
            "<b>Title:</b> %{customdata[0]}<br>"
            "<b>Location:</b> %{customdata[1]}<br>"
            "<b>Intensity:</b> %{customdata[2]}<br>"
            "<b>Scale:</b> %{customdata[3]}<br>"
            "<extra></extra>"  # Remove additional info
        )
    ))

    # Update map layout
    fig.update_layout(
        mapbox=dict(
            style="open-street-map",  # Map style
            center=dict(lat=df['latitude'].iloc[-1], lon=df['longitude'].iloc[-1]),  # Map center
            zoom=4.4  # Zoom level
        ),
        margin=dict(r=0, t=0, l=0, b=0)  # Graph margins
    )
    return dropdown_options, initial_value, fig

# Callback to update description and publication date
@app.callback(
    Output('description-date', 'children'),
    [Input('title-dropdown', 'value')]
)
def update_description_data(selected_date):
    df = update_data()
    row = df[df['date'] == selected_date]
    if not row.empty:
        description = html.Table(
            style={"text-align": "left", "font-size":"15px"},
            children=[
                html.Tr([html.Th("Time: "), html.Td(row['date'])]),
                html.Tr([html.Th("Epicenter: "), html.Td(row['location'])]),
                html.Tr([html.Th("Intensity (MMI): "), html.Td(row['intensity'])]),
                html.Tr([html.Th("Magnitude: "), html.Td(row['scale'])])
            ])
        return description
    else:
        return html.Div("No data available")

@app.callback(
    Output('more-info-div', 'className'),
    Input('hide-store', 'data')
)
def update_styles(data):
    hide = data['hide']
    if hide:
        return 'more-info-div hidden'
    else:
        return 'more-info-div visible'

@app.callback(
    Output('hide-store', 'data'),
    Input('triguer', 'n_clicks'),
    prevent_initial_call=True
)
def toggle_hide(n_clicks):
    if n_clicks is None:
        raise dash.exceptions.PreventUpdate
    return {'hide': n_clicks % 2 == 1}

if __name__ == '__main__':
    app.run_server(host='0.0.0.0', port=8050, debug=False)
